name: brasil_fields
description: O jeito mais fácil de utilizar padrões e formatos brasileiros em seu projeto Dart.
version: 1.1.4
homepage: https://github.com/rubensdemelo/brasil_fields

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  pedantic: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
