name: publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-java@v3.7.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2.8.0
      - run: flutter pub get
      - run: flutter test
      - uses: codecov/codecov-action@v3.1.1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          baseHref: /brasil_fields/
